Models/ConvertedTimezoneDetailViewModel.cs
namespace TimezoneConverterWebApp.Models
{
    public class ConvertedTimezoneDetailViewModel
    {
        public DateTime? OriginalStartDateTime { get; set; }
        public DateTime? OriginalEndDateTime { get; set; }
        public DateTime? ConvertedAdminStartDateTime { get; set; }
        public DateTime? ConvertedAdminEndDateTime { get; set; }
        public DateTime? ConvertedDeadlineStartDateTime { get; set; }
        public DateTime? ConvertedDeadlineEndDateTime { get; set; }
        public DateTime? ConvertedOutlookStartDateTime { get; set; }
        public DateTime? ConvertedOutlookEndDateTime { get; set; }
        public DateTime? ConvertedUserStartDateTime { get; set; }
        public DateTime? ConvertedUserEndDateTime { get; set; }
        public TimezoneViewModel? SelectedTimezones { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace TimezoneConverterWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/TimezoneModel.cs
namespace TimezoneConverterWebApp.Models
{
    public class TimezoneModel
    {
        public string? Id { get; set; }
        public bool HasIanaId { get; set; }
        public string? DisplayName { get; set; }
        public string? StandardName { get; set; }
        public string? DaylightName { get; set; }
        public bool? SupportsDaylightSavingTime { get; set; }

    }
}

Models/TimezoneViewModel.cs
namespace TimezoneConverterWebApp.Models
{
    public class TimezoneViewModel
    {
        public string? DeadlineTimezone { get; set; }
        public string? FirmAdminTimezone { get; set; }
        public string? OutlookCalendarTimezone { get; set; }
        public string? UserTimezone { get; set; }
        public DateTime StartDateTime { get; set; }
        public DateTime EndDateTime { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Text.Json;
using TimezoneConverterWebApp.Models;


namespace TimezoneConverterWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TimezoneController.cs
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using System.Text.Json;
using TimezoneConverterWebApp.Models;

namespace TimezoneConverterWebApp.Controllers
{
    public class TimezoneController : Controller
    {
        public IActionResult Index()
        {
            string jsonFilePath = "timezones.json";
            string jsonContent = System.IO.File.ReadAllText(jsonFilePath);
            List<TimezoneModel> timezones = JsonSerializer.Deserialize<List<TimezoneModel>>(jsonContent);
            return View(timezones);
        }

        [HttpPost]
        public IActionResult ConvertToTimezone([FromForm] TimezoneViewModel timezoneViewModel)
        {
            //DateTime.TryParseExact(timezoneViewModel.StartDateTime, "MM/dd/yyyy hh:mm tt",CultureInfo.InvariantCulture,DateTimeStyles.None, out DateTime parsedStartDateTime);
            //DateTime.TryParseExact(timezoneViewModel.EndDateTime, "MM/dd/yyyy hh:mm tt",CultureInfo.InvariantCulture,DateTimeStyles.None, out DateTime parsedEndDateTime);
            var timezoneInfo = ConvertUserTimeZone(timezoneViewModel.StartDateTime, timezoneViewModel.EndDateTime, timezoneViewModel?.DeadlineTimezone, timezoneViewModel?.UserTimezone, timezoneViewModel?.FirmAdminTimezone, timezoneViewModel?.OutlookCalendarTimezone);

            return PartialView(timezoneInfo);
        }



        private static ConvertedTimezoneDetailViewModel ConvertUserTimeZone(DateTime startDateTime, DateTime endDateTime, string deadlineTimeZone, string userTimeZone, string firmAdminTimeZone, string outlookTimezone)
        {
            
            DateTime deadlineStartDateTime = startDateTime;
            DateTime deadlineEndDateTime = endDateTime;

            // get TimeZone info for user, appointment and firm admin
            TimeZoneInfo deadlineTimeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(deadlineTimeZone);
            TimeZoneInfo userTimeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(userTimeZone);
            TimeZoneInfo firmAdminTimeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(firmAdminTimeZone);
            TimeZoneInfo outlookCalendarTimeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(outlookTimezone);

            #region step 1: convert deadlineTimezone to adminTimeZone and save in db
            DateTime convertedAdminStartDateTime = TimeZoneInfo.ConvertTime(deadlineStartDateTime, deadlineTimeZoneInfo, firmAdminTimeZoneInfo);
            DateTime convertedAdminEndDateTime = TimeZoneInfo.ConvertTime(deadlineEndDateTime, deadlineTimeZoneInfo, firmAdminTimeZoneInfo);
            #endregion

            #region Step 2: convert the adminTimeZone back to deadlineTimezone while adding to calendar event
            DateTime convertedDeadlineStartDateTime = TimeZoneInfo.ConvertTime(convertedAdminStartDateTime, firmAdminTimeZoneInfo, deadlineTimeZoneInfo);
            DateTime convertedDeadlinEndDateTime = TimeZoneInfo.ConvertTime(convertedAdminEndDateTime, firmAdminTimeZoneInfo, deadlineTimeZoneInfo);
            #endregion

            #region Step 3: convert firm admin timezone to logged in user timezone when fetching for deadline chart
            DateTime convertedUserStartDateTime = TimeZoneInfo.ConvertTime(convertedAdminStartDateTime, firmAdminTimeZoneInfo, userTimeZoneInfo);
            DateTime convertedUserEndDateTime = TimeZoneInfo.ConvertTime(convertedAdminEndDateTime, firmAdminTimeZoneInfo, userTimeZoneInfo);
            #endregion

            #region Step 4: convert the deadlineTimezone to user timezone in calendar
            DateTime convertedOutlookStartDateTime = TimeZoneInfo.ConvertTime(convertedDeadlineStartDateTime, deadlineTimeZoneInfo, outlookCalendarTimeZoneInfo);
            DateTime convertedOutlookEndDateTime = TimeZoneInfo.ConvertTime(convertedDeadlinEndDateTime, deadlineTimeZoneInfo, outlookCalendarTimeZoneInfo);
            #endregion

            ConvertedTimezoneDetailViewModel convertedTimezoneDetail = new() 
            { 
                OriginalStartDateTime = deadlineStartDateTime,
                OriginalEndDateTime = deadlineEndDateTime,
                ConvertedAdminStartDateTime = convertedAdminStartDateTime,
                ConvertedAdminEndDateTime = convertedAdminEndDateTime,
                ConvertedDeadlineStartDateTime = convertedDeadlineStartDateTime,
                ConvertedDeadlineEndDateTime = convertedDeadlinEndDateTime,
                ConvertedOutlookStartDateTime = convertedOutlookStartDateTime,
                ConvertedOutlookEndDateTime = convertedOutlookEndDateTime,
                ConvertedUserStartDateTime = convertedUserStartDateTime,
                ConvertedUserEndDateTime = convertedUserEndDateTime,
                SelectedTimezones = new ()
                {
                    FirmAdminTimezone = firmAdminTimeZone,
                    DeadlineTimezone = deadlineTimeZone,
                    OutlookCalendarTimezone = outlookTimezone,
                    UserTimezone = userTimeZone
                }
            };

            return convertedTimezoneDetail;

        }
    }
}

Views/Home/Index.cshtml
<h4>Homepage</h4>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TimezoneConverterWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TimezoneConverterWebApp.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TimezoneConverterWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Timezone" asp-action="Index">Timezone</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - TimezoneConverterWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/js/home.js" asp-append-version="true"></script>
    <script src="~/js/timezone.js" asp-append-version="true"></script>
    
</body>
</html>

Views/Timezone/ConvertToTimezone.cshtml
@model ConvertedTimezoneDetailViewModel


<p class="card-text"><b>Original StartDateTime:</b> @Model.OriginalStartDateTime</p>
<p class="card-text"><b>Original EndDateTime:</b> @Model.OriginalEndDateTime</p>
<br />

<p class="card-text"><b>DeadlineTimeZone:</b> @Model.SelectedTimezones?.DeadlineTimezone</p>
<p class="card-text"><b>Converted Deadline StartDateTime:</b> @Model.ConvertedDeadlineStartDateTime</p>
<p class="card-text"><b>Converted Deadline EndDateTime:</b> @Model.ConvertedDeadlineEndDateTime</p>
<br />

<p class="card-text"><b>FirmAdminTimeZone:</b> @Model.SelectedTimezones?.FirmAdminTimezone</p>
<p class="card-text"><b>Converted Admin StartDateTime:</b> @Model.ConvertedAdminStartDateTime</p>
<p class="card-text"><b>Converted Admin EndDateTime:</b> @Model.ConvertedAdminEndDateTime</p>
<br />

<p class="card-text"><b>OutlookCalendarTimeZone:</b> @Model.SelectedTimezones?.OutlookCalendarTimezone</p>
<p class="card-text"><b>Converted Deadline StartDateTime:</b> @Model.ConvertedOutlookStartDateTime</p>
<p class="card-text"><b>Converted Deadline EndDateTime:</b> @Model.ConvertedOutlookEndDateTime</p>
<br />

<p class="card-text"><b>UserTimeZone:</b> @Model.SelectedTimezones?.UserTimezone</p>
<p class="card-text"><b>Converted User StartDateTime:</b> @Model.ConvertedUserStartDateTime</p>
<p class="card-text"><b>Converted User EndDateTime:</b> @Model.ConvertedUserEndDateTime</p>
<br />

Views/Timezone/Index.cshtml
@model List<TimezoneModel>

@{
    ViewData["Title"] = "Timezone Converter";

}

<div class="text-center">
    <h1 class="display-4">TimeZone Converter</h1>
</div>

<div class="row">
    <div class="col-sm-6 mb-3 mb-sm-0">
        <div class="card">
            <div class="card-header">
                Appointment Details
            </div>
            <div class="card-body">
                <form method="post">
                    <div class="mb-3">
                        <label for="startDateTime" class="form-label">Start Date Time</label>
                        <input type="datetime-local" class="form-control" id="startDateTime" name="StartDateTime" value="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")">
                    </div>
                    <div class="mb-3">
                        <label for="endDateTime" class="form-label">End Date Time</label>
                        <input type="datetime-local" class="form-control" id="endDateTime" name="EndDateTime" value="@DateTime.Now.AddMinutes(30.00).ToString("yyyy-MM-ddTHH:mm")">
                    </div>
                    <div class="mb-3">
                        <label for="deadlineTimezone" class="form-label">Select Deadline Timezone</label>
                        <select id="deadlineTimezone" class="form-select" name="DeadlineTimezone" aria-label="deadline timezone">
                            <option value="" selected>-- Select Timezone --</option>
                            @foreach (var timezone in Model)
                            {
                                <option value=@timezone.Id>@timezone.DisplayName</option>
                            }
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="firmAdminTimezone" class="form-label">Select Firm Admin Timezone</label>
                        <select id="firmAdminTimezone" class="form-select" name="FirmAdminTimezone" aria-label="firm admin timezone">
                            <option value="" selected>-- Select Timezone --</option>
                            @foreach (var timezone in Model)
                            {
                                <option value=@timezone.Id>@timezone.DisplayName</option>
                            }
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="outlookCalendarTimezone" class="form-label">Select Outlook Calendar Timezone</label>
                        <select id="outlookCalendarTimezone" class="form-select" name="OutlookCalendarTimezone" aria-label="outlook calendar timezone">
                            <option value="" selected>-- Select Timezone --</option>
                            @foreach (var timezone in Model)
                            {
                                <option value=@timezone.Id>@timezone.DisplayName</option>
                            }
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="userTimezone" class="form-label">Select User Timezone</label>
                        <select id="userTimezone" class="form-select" name="UserTimezone" aria-label="user timezone">
                            <option value="" selected>-- Select Timezone --</option>
                            @foreach (var timezone in Model)
                            {
                                <option value=@timezone.Id>@timezone.DisplayName</option>
                            }
                        </select>
                    </div>

                    <button type="submit" id="btnSubmitConvert" class="btn btn-primary mb-3">Convert</button>
                </form>

            </div>
        </div>
    </div>
    <div class="col-sm-6 mb-3 mb-sm-0">
        <div class="card">
            <div class="card-header">
                Appointment Conversion Details
            </div>
            <div class="card-body">
                <div id="dvConvertedDetails"></div>
            </div>
        </div>
    </div>
</div>


@section scripts {
    <script>
        $(document).ready(function () {
            $('#deadlineTimezone').select2({
                width: "100%"
            });
            $('#firmAdminTimezone').select2({
                width: "100%"
            });
            $('#outlookCalendarTimezone').select2({
                width: "100%"
            });
            $('#userTimezone').select2({
                width: "100%"
            });
        });
    </script>
}